server:
  port: 9081
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    #连接到本地计算机上的 MySQL 数据库，数据库名称为 blog，使用 Unicode 编码和 UTF-8 字符集，同时设置时区为 UTC，以确保时间的准确性和字符的正确显示。
    #useSSL=false：这个参数的设置表示在与 MySQL 数据库建立连接时不启用 SSL 加密
    url: jdbc:mysql://localhost:3306/gotodo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
logging:
  level:
    com.springleaf.gotodo.mapper: DEBUG
    org.apache.ibatis: DEBUG
    org.apache.ibatis.logging.stdout.StdOutImpl: DEBUG